### ISSUE TITLE
Setting nginx credentials failed, remained default

### ISSUE THREAD

**Issue by svollath** [SUSE/stratos-metrics#30]
I deployed metrics to CaaSP3 as well as to Azure AKS - in both cases the nginx credentials remained default:

```
> kubectl logs stratos-metrics-cfdevio-fcdc877bb-55mkm -n metrics
Checking if certificate has been supplied!
TLS certificate detected continuing, starting nginx.
Create username/password for authentication
Adding password for user metrics
Starting nginx
```

while my metrics-config-values.yaml contained (e.g. azure):

```
secrets:
  CLUSTER_ADMIN_PASSWORD: password
  UAA_ADMIN_CLIENT_SECRET: password
env:
  DOMAIN: 40.68.160.43.omg.howdoi.website
  UAA_HOST: uaa.40.68.160.43.omg.howdoi.website
  UAA_PORT: 2793
  GARDEN_ROOTFS_DRIVER: "overlay-xfs"
kube:
  external_ips: ["10.240.0.6", "10.240.0.5", "10.240.0.4"]
  storage_class:
    persistent: "default"
    shared: "shared"
  registry:
    hostname: "registry.suse.com"
    username: ""
    password: ""
  organization: "cap"
  auth: "rbac"
  psp:
    nonprivileged: "suse.cap.psp"
    privileged: "suse.cap.psp"
---
kubernetes:
  authEndpoint: https://svollath-svollath-cap-aks-f416cc-f0ebd67d.hcp.westeurope.azmk8s.io:443
prometheus:
  kubeStateMetrics:
    enabled: true
  imagePullSecrets:
  - name: regsecret
nginx:
  username: admin
  password: password
```

```
helm install suse/metrics --name metrics --namespace metrics -f metrics-config-values.yaml
```
